# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dcxdemo-frontend-website

on:
  push:
    paths:
      - "dcx-genai-dev-studion/**"
    branches:
      - mainv3
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dcxgenai.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_127fb83cdfc04689af11f56f4baa6e77 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9f92eda090e8417099899a381e129e0e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dcxgenai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_127fb83cdfc04689af11f56f4baa6e77 }}/dcx-genai-dev-studion-image:${{ github.sha }}
        file: dcx-genai-dev-studion/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dcxdemo-frontend-website'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_58640e6e9e0148cfa2a974946795f793 }}
        images: 'dcxgenai.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_127fb83cdfc04689af11f56f4baa6e77 }}/dcx-genai-dev-studion-image:${{ github.sha }}'
